[package]
name = "fastflow"
description = "rust binding of generalized and pauli flow finding algorithms."
homepage = "https://github.com/TeamGraphix/fastflow"
repository = "https://github.com/TeamGraphix/fastflow"
version = "0.1.0"
authors = ["S.S <66886825+EarlMilktea@users.noreply.github.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
keywords = ["mbqc", "quantum-computing", "quantum"]

[lib]
name = "fastflow"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
fixedbitset = "0.5"
pyo3 = { version = "0.21", features = ["abi3-py38"] }

[dev-dependencies]
rand = "0.8"
rstest = "0.21"
rstest_reuse = "0.7"
