[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "fastflow"
# Must be consistent with Cargo.toml
version = "0.1.0"
dependencies = ["eval_type_backport", "networkx", "types-networkx", "pydantic"]
requires-python = ">=3.8,<3.13"

[project.optional-dependencies]
dev = ["mypy", "pytest", "pytest-cov", "ruff"]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
module-name = "fastflow._impl"

[tool.mypy]
python_version = "3.8"

[tool.ruff]
line-length = 120
extend-include = ["*.ipynb"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  # Conclicts with ruff format
  "W191",
  "E111",
  "E114",
  "E117",
  "D206",
  "D300",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "COM812",
  "COM819",
  "ISC001",
  "ISC002",

  # Not necessary for this project
  "ASYNC",
  "DJ",
  "PD",
  "AIR",

  # Manually disabled
  "C90",   # mccabe
  "COM",   # commas
  "FBT",   # boolean-trap
  "T20",   # print
  "TD",    # todo
  "FIX",   # fixme
  "ERA",   # eradicate
  "ANN10", # `self`/`cls` not annotated
  "D105",  # undocumented magic method
  "D203",  # blank line before class (conflicts with D211)
  "D213",  # break after `"""` in docstring (conflicts with D212)
  "S101",  # `assert` detected
  "T20",   # `print`/`pprint` detected
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.extend-per-file-ignores]
"scratchpad/*.py" = ["INP"]
