name: check_rs

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_rs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          rustup update
          # Use nightly for rustfmt
          rustup toolchain install --allow-downgrade nightly
          rustup component add --toolchain nightly rustfmt

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Run rustfmt
        run: |
          cargo +nightly fmt -- --check

      - name: Run clippy
        run: |
          cargo clippy -- -D warnings
