name: check_py

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Setup Ruff
        run: |
          python3 -m pip install -U pip
          pip install ruff

      - name: Run ruff check
        run: |
          pip install ruff
          ruff check

      - name: Run ruff isort
        run: |
          ruff check --select I --fix

      - name: Run ruff format
        run: |
          ruff format

  staticcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - run: |
          python3 -m pip install -U pip
          pip install .[dev]

      - name: Run mypy
        run: |
          mypy .

      - name: Run pyright
        run: |
          pyright .
