name: check_py

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Setup Ruff
        run: |
          python3 -m pip install -U pip
          pip install ruff

      - name: Run ruff check
        run: |
          pip install ruff
          ruff check

  ruff_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Setup Ruff
        run: |
          python3 -m pip install -U pip
          pip install ruff

      - name: Run ruff format
        run: |
          ruff format

      - name: Run ruff isort
        run: |
          ruff check --select I --fix

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Run mypy
        run: |
          python3 -m pip install -U pip
          pip install mypy
          pip install .[dev]
          mypy .

  pyre:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Run pyre
        run: |
          python3 -m pip install -U pip
          pip install pyre-check
          pip install .[dev]
          pyre

  pyright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Run pyright
        run: |
          python3 -m pip install -U pip
          pip install pyright
          pip install .[dev]
          pyright .
