name: cov

on: [push, pull_request]

permissions:
  contents: read

jobs:
  cov_py:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v5

      - name: Measure Python coverage
        run: |
          uv sync --extra dev
          uv run pytest --cov-report=xml --cov-report=term --cov --cov-branch

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: python

  cov_rs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-tarpaulin

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Measure Rust coverage
        run: |
          cargo tarpaulin --out Xml

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: rust
