name: cov

on: [push, pull_request]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-tarpaulin

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Measure Python coverage
        run: |
          python3 -m pip install -U pip
          pip install pipenv
          # Use development build
          pipenv install -e .[dev]
          pipenv run pytest --cov=./python --cov-report=xml

      - name: Measure Rust coverage
        run: |
          cargo tarpaulin --out Xml

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
