name: doc

on: [pull_request, push, workflow_dispatch]

permissions:
  contents: read

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          python3 -m pip install -U pip
          pip install -e .[dev,doc]

      - run: sphinx-build docs/source docs/build -W -a

      - uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: ./docs/build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/build
          retention-days: "1"

  deploy_docs:
    runs-on: ubuntu-latest

    needs: build_docs

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
