name: wheel

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        target: [x64, x86]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: ${{ matrix.target }}

      - name: Update pip
        run: |
          python3 -m pip install -U pip

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist

      - name: Install from wheel
        shell: bash
        run: |
          pip install dist/fastflow-*.whl --force-reinstall
          python3 -c "import fastflow"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/

  macos:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: x64

      - name: Update pip
        run: |
          python3 -m pip install -U pip

      - name: Build wheels - x86_64
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          args: --release --out dist --sdist

      - name: Install built wheel - x86_64
        run: |
          pip install dist/fastflow-*x86_64.whl --force-reinstall
          python3 -c "import fastflow"

      - name: Build wheels - universal2
        uses: PyO3/maturin-action@v1
        with:
          target: universal2-apple-darwin
          args: --release --out dist

      - name: Install from wheel - universal2
        run: |
          pip install dist/fastflow-*universal2.whl --force-reinstall
          python3 -c "import fastflow"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist/
