name: wheel

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        target: [x64, x86]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: ${{ matrix.target }}

      - run: |
          python3 -m pip install -U pip

      - uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist

      - shell: bash
        run: |
          pip install dist/fastflow-*.whl --force-reinstall
          python3 -c "import fastflow"

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-windows-${{ matrix.target }}
          path: dist/

  macos-x86_64:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: x64

      - run: |
          python3 -m pip install -U pip

      - uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          args: --release --out dist --sdist

      - run: |
          pip install dist/fastflow-*.whl --force-reinstall
          python3 -c "import fastflow"

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-macos-x86_64
          path: dist/

  macos-universal2:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: x64

      - run: |
          python3 -m pip install -U pip

      - uses: PyO3/maturin-action@v1
        with:
          target: universal2-apple-darwin
          args: --release --out dist

      - run: |
          pip install dist/fastflow-*.whl --force-reinstall
          python3 -c "import fastflow"

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-macos-universal2
          path: dist/

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64, i686]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: x64

      - uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          args: --release --out dist

      - if: matrix.target == 'x86_64'
        run: |
          pip install dist/fastflow-*.whl --force-reinstall
          python -c "import fastflow"

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-linux-${{ matrix.target }}
          path: dist/

  musllinux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64, i686]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: x64

      - uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}-unknown-linux-musl
          manylinux: musllinux_1_2
          args: --release --out dist

      - name: Install and test with alpine
        if: matrix.target == 'x86_64'
        uses: addnab/docker-run-action@v3
        with:
          image: alpine:latest
          options: --mount type=bind,src=${{ github.workspace }},dst=/io
          run: |
            apk add py3-pip
            pip3 install -U pip
            pip3 install /io/dist/fastflow-*.whl
            python3 -c "import fastflow"

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-musllinux-${{ matrix.target }}
          path: dist/
