name: wheel_windows

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x64, x86]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: ${{ matrix.target }}

      - name: Update pip
        run: |
          python3 -m pip install -U pip

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist

      - name: Install from wheel
        run: |
          pip install dist/fastflow*.whl --force-reinstall
          python -c "import fastflow"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist
