name: wheel_macos

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          architecture: x64

      - name: Update pip
        run: |
          python3 -m pip install -U pip

      - name: Build wheels - x86_64
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          args: --release --out dist --sdist

      - name: Install built wheel - x86_64
        run: |
          pip install fastflow --no-index --find-links dist --force-reinstall
          python -c "import fastflow"

      - name: Build wheels - universal2
        uses: PyO3/maturin-action@v1
        with:
          args: --release --universal2 --out dist

      - name: Install from wheel - universal2
        run: |
          pip install fastflow --no-index --find-links dist --force-reinstall
          python -c "import fastflow"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist
